### ISSUE TITLE
Time picker inner container color can't be changed

### ISSUE THREAD

**Issue by halfawatermelon** [marosseleng/compose-material3-datetime-pickers#66]
I tried out changing all the colors of the time picker to a dark theme, but found that the color of the switch and dial container can't be accessed. ContainerColor only changes the outer container.
![timer](https://user-images.githubusercontent.com/50372825/212778110-019af73a-0a2d-493b-b1b2-1bae46c797be.PNG)

To clarify i have used all the accessible colors.
![colors](https://user-images.githubusercontent.com/50372825/212778385-d4439977-d7fe-4195-a82d-a6b1f7fdd502.PNG)

**Comment by marosseleng** [comment]
Hi, thanks for the input! The inner container background color is probably not changing because of `TimePicker`'s root `Composable` which is `Surface` (which will be fixed, together with further API clarification). Could you please try changing your `MaterialTheme.colorScheme.surface` color to see if it changes?

As for the switch, I might not be entirely sure what you are referring to.

Also, if applicable here, for now, you could probably try changing the colors in your `MaterialTheme` declaration, the `TimePickerDialog` might then behave correctly.
